# -*- coding: utf-8 -*-
"""Untitled4.r

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zvg_zyunGiOurDv0mF3LsJ4jJ8H1M_RJ
"""

# Load required libraries
library(ggplot2)
library(lattice)
library(caret)
library(randomForest)

# Load the dataset
data <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data", header = FALSE)

# Assign column names
colnames(data) <- c("ID", "Diagnosis", paste("V", 1:30, sep = ""))

# Remove unnecessary columns
data <- data[, -1] # Removing the ID column

# Convert Diagnosis column to factor
data$Diagnosis <- factor(data$Diagnosis, levels = c("B", "M"), labels = c("Benign", "Malignant"))

# Set seed for reproducibility
set.seed(123)

# Split the data into training and testing sets (70% training, 30% testing)
trainIndex <- createDataPartition(data$Diagnosis, p = 0.7, list = FALSE)
trainData <- data[trainIndex, ]
testData <- data[-trainIndex, ]

# Train the random forest model
model <- randomForest(Diagnosis ~ ., data = trainData, ntree = 500)
# Predict on test data
predictions <- predict(model, testData)
# Confusion matrix
confusionMatrix(predictions, testData$Diagnosis)